export const BOARD = {
  STATE: "state",
  CBSE: "cbse",
  ICSE: "icse",
  OTHER: "other"
};

export const SUBJECT_INTERESTS = {
  MATH_PHYSICS: "math_physics",
  BIOLOGY_CHEMISTRY: "biology_chemistry",
  HANDS_ON_TECHNICAL: "hands_on_technical",
  COMMERCE_ACCOUNTS: "commerce_accounts",
  CIVICS_HISTORY: "civics_history",
  CREATIVE_DESIGN: "creative_design"
};

export const PATHWAY_KEYS = {
  MPC_ENGINEERING: "MPC_ENGINEERING",
  BIPC_MEDICINE: "BIPC_MEDICINE",
  POLYTECHNIC_DIPLOMA: "POLYTECHNIC_DIPLOMA",
  MEC_COMMERCE_DATA: "MEC_COMMERCE_DATA",
  CEC_COMMERCE_MANAGEMENT: "CEC_COMMERCE_MANAGEMENT",
  HEC_HUMANITIES_ARTS: "HEC_HUMANITIES_ARTS",
  ARTS_DESIGN_CREATIVE: "ARTS_DESIGN_CREATIVE"
};